### ISSUE TITLE
Context action seems not activated by ';' key

### ISSUE THREAD

**Issue by wdicarlo** [dakaraphi/eclipse-plugin-commander#29]
Whenever I try to activate the context action with the ';' key the corresponding context mode is not activate.

For example, here are the steps I have tried:
1. Activate the Finder
1. Press the ';' key
1. The context mode is not activated

**Comment by dakaraphi** [comment]
@wdicarlo does it work from the `Commander` dialog?

After opening `Finder`.  Do you have anything in the view highlighted or selected prior to pressing `;`?

**Comment by wdicarlo** [comment]
It should not need to select anything in case I just want to sort the list

**Comment by wdicarlo** [comment]
In any case, even selecting some entry the ';' key is not working

**Comment by dakaraphi** [comment]
Just trying to understand under what condition it works or not for you.

Does it also not work in `Commander` ?

Does the `tab` key work for toggling the display mode from `working` and `discovery` ?

**Comment by wdicarlo** [comment]
';' is not working also with Commander. 

Tab key is working. 

Note that I am using an Italian keyboard, However, the key code should not change.

**Comment by dakaraphi** [comment]
When you press `;` is it printed inside the input field?

If it is not printed, then it suggests it is being handled.  If you open Eclipse Error Log, do you see any errors added when you press the `;` key?

**Comment by wdicarlo** [comment]
The key is printed in the input field. I have got the following exception but selecting a couple of entries in the commander and pressing the ';' key which get printed in the input field:
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.ArrayIndexOutOfBoundsException)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

**Comment by wdicarlo** [comment]
Note that I have installed also the Vrapper plugin, but I disabled it while trying your plugin in order to be sure to not interfere with key handling.

**Comment by dakaraphi** [comment]
Not sure what is generating that stack trace.  There is nothing related to the plugin in the stack.

If the key is printed, then the keycode didn't match.

FYI, if you want to take a peek.  The code that handles the keys is here: line 303
https://github.com/dakaraphi/eclipse-plugin-commander/blob/master/dakara.eclipse.commander.plugin/src/dakara/eclipse/plugin/kavi/picklist/KaviList.java

I'm not sure what should change here.  I will have to look into it unless you happen to know.

**Comment by wdicarlo** [comment]
I have tried with another instance of Eclipse, but I have got the same issue. However, this time I have got some more info:
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.ArrayIndexOutOfBoundsException: -38)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -38
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at dakara.eclipse.plugin.kavi.picklist.KaviList.fastSelectItem(KaviList.java:141)
	at dakara.eclipse.plugin.kavi.picklist.KaviList.lambda$3(KaviList.java:105)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 23 more

**Comment by dakaraphi** [comment]
Do you know if this exception occurred at the time of pressing `;` ?

This exception is related to fast select.  That is when you enter `/` followed by an alpha index to select something in the list.

**Comment by wdicarlo** [comment]
These are the steps I have done:

1. Open Commander
1. Type one or two /
1. Type ;
1. The exception is generated systematically

**Comment by dakaraphi** [comment]
I don't know why you are getting that exception yet.

However, I think I know what I need to change for the `;` to work.  I'm currently matching on the keycode of the event.  Looks like the Italian keyboard has `,` and `;` as the same key vs. US which has `;` and `:` as the same key.  The SWT event also has a `char` property which I should test instead of the keycode.

**Comment by dakaraphi** [comment]
@wdicarlo you can try a beta build with a fix using this update site location
https://raw.githubusercontent.com/dakaraphi/eclipse-updatesite/beta/dakara.eclipse.updatesite/site.xml

**Comment by wdicarlo** [comment]
Now, I can use the ';' key. Good job. So I close the ticket, but I am facing other exceptions. Let me investigate a little bit more and in case I will open another issue.
